config/routes.rb
Dbauth::Application.routes.draw do

  resources :jobs

  resources :people do
    collection do
      get 'find'
    end
  end

  resources :companies

  resources :roles do
    member do
      post 'add_user'
      delete 'remove_user'
    end
  end

  resources :users, :only => [:index, :show, :new, :create, :edit, :update] do
    collection do
      get 'find'
    end
  end

  resources :password_changes, :only => [:new, :create]

  resources :password_recoveries, :only => [:new, :create, :edit, :update]

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  root :to => 'admin#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :jobs

  def self.statuses
    %w(active inactive)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @q = Person.search(params[:q])
    @people = @q.result(distinct: true).paginate(:page => params[:page])
  end

  def find
    @q = Person.search(params[:q])
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :status)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Entering User</h3>
  </div>
  <div class="panel-body">

  <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="form-group">
    <%= f.label :status %><br>
    <%= f.select :status, Person.statuses, :include_blank => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/find.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Find Person</h3>
  </div>
  <div class="panel-body">
    <%= search_form_for @q do |f| %>
      <div class="form-group">
        <%= f.label :first_name_cont %>
        <%= f.text_field :first_name_cont %>
      </div>
      <div class="form-group">
        <%= f.label :last_name_cont %>
        <%= f.text_field :last_name_cont %>
      </div>

      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/people/index.html.erb
<table class="table table-condensed table-bordered table-hover">
  <thead>
    <tr>
      <th></th>
      <th>First name</th>
      <th>Last name</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to 'Show', person %></td>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Person</h3>
  </div>
  <div class="panel-body">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>First name:</strong>
      <%= @person.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= @person.last_name %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= @person.status %>
    </p>
  </div>

</div>
<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>