config/routes.rb
Dbauth::Application.routes.draw do

  resources :jobs

  resources :people do
    collection do
      get 'find'
    end
  end

  resources :companies

  resources :roles do
    member do
      post 'add_user'
      delete 'remove_user'
    end
  end

  resources :users, :only => [:index, :show, :new, :create, :edit, :update] do
    collection do
      get 'find'
    end
  end

  resources :password_changes, :only => [:new, :create]

  resources :password_recoveries, :only => [:new, :create, :edit, :update]

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  root :to => 'admin#index'

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users

  def self.roles
    %w(admin).map {|name| Role.find_or_create_by(:title => name)}
  end
  
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  filter_access_to :all

  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  def add_user
    user = User.find(params[:user_id])
    role = Role.find(params[:id])
    role.users << user unless role.users.include?(user)
    redirect_to role_path(role)
  end

  def remove_user
    user = User.find(params[:user_id])
    role = Role.find(params[:id])
    role.users.delete(user)
    redirect_to role_path(role)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:title)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
  def users_left_to_add
    (User.active-@role.users).sort_by {|user| user.last_first}.map {|user| [user.last_first, user.id]}
  end
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<table class="table table-condensed table-bordered table-hover">
  <thead>
    <tr>
      <th><%= link_to 'New Role', new_role_path %></th>
      <th>Title</th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= link_to 'Show', role %></td>
        <td><%= role.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Role: <%= @role.title %></h3>
  </div>
  <div class="panel-body">
    <p id="notice"><%= notice %></p>


    <%= form_tag add_user_role_path(@role), :method => :post do %>
      <strong>Add User:</strong>
      <%= select_tag :user_id, options_for_select(users_left_to_add), :include_blank => true %>
      <%= submit_tag 'Add User' %>
    <% end %>



    <table class="table table-bordered table-condensed table-hover">
      <thead>
        <th></th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>E-mail</th>
        <th></th>
      </thead>
      <tbody>
        <% @role.users.each do |user| %>
          <tr>
            <td><%= link_to 'Show', user_path(user) %></td>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
            <td><%= link_to 'Remove User', remove_user_role_path(@role, :user_id => user.id), :method => :delete, :confirm => "Remove user?" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

<%= link_to 'Back', roles_path %>