config/routes.rb
Dbauth::Application.routes.draw do

  resources :jobs

  resources :people do
    collection do
      get 'find'
    end
  end

  resources :companies

  resources :roles do
    member do
      post 'add_user'
      delete 'remove_user'
    end
  end

  resources :users, :only => [:index, :show, :new, :create, :edit, :update] do
    collection do
      get 'find'
    end
  end

  resources :password_changes, :only => [:new, :create]

  resources :password_recoveries, :only => [:new, :create, :edit, :update]

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  root :to => 'admin#index'

end

app/views/layouts/_messages.html.erb
<% unless flash[:notice].blank? %>
  <div class="row">
    <div class="alert alert-info col-md-6 centered"><%=raw flash[:notice] %></div>
  </div>
<% end %>

<% unless flash[:alert].blank? %>
  <div class="row">
    <div class="alert alert-danger col-md-6 centered"><%=raw flash[:alert] %></div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="collapse navbar-collapse">
  <ul class="nav navbar-nav">

    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">User Accounts<b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Find Account', find_users_path %></li>
        <li><%= link_to 'Show All', users_path %></li>
      </ul>
    </li>

    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">People<b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Find Person', find_people_path %></li>
        <li><%= link_to 'Show All', people_path %></li>
      </ul>
    </li>
    <li><%= link_to 'Roles', roles_path %></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.full_name %><b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><%= link_to 'Change Password', new_password_change_path %></li>
        <li><%= link_to 'Logout', logout_path %></li>
      </ul>
    </li>
  </ul>
</div><!--/.nav-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dbauth</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'DbAuth', root_url, :class => 'navbar-brand' %>
        </div>
        <%= current_user ? render('layouts/navigation') : '' %>
      </div>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>

</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dbauth</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>

</html>